### ISSUE TITLE
[easy] I want to be able to generate a display that can be passed over Artnet/DMX to the PixLite 16 MkII controller.

### ISSUE THREAD

**Issue by connorgmeehan** [connorgmeehan/memories-ofApp#11]
- [ ] #7 [hard] I want to be able to get the positions of each person in the scene
 - [ ] #8 [easy] I want to be able to create an object that is generated when someone enters the scene and follows their XZ coordinates until they leave the scene.
 - [ ] #9 [easy] I want this these objects to have an implemented draw function.
 - [ ] #10 [hard] I want to get the rendered output of the display as an FBO and pass the data over Artnet to our PixLite controller.
